urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
from experimentdb.datasets.models import SGD_GeneNames, SGD_phenotypes, PI35P2_Binding_Screen_SP

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^accounts/login/', 'django.contrib.auth.views.login'),
	(r'^comments?/', include('django.contrib.comments.urls')),
	(r'^search/$', 'experimentdb.views.search'),
	(r'^ajax_select/', include('ajax_select.urls')),
	(r'^add/protein_family/?$', 'experimentdb.proteins.views.newProteinFamily'),

	(r'^experiments?/', include('experimentdb.data.urls.experiment')),
	(r'^exps?/', include('experimentdb.data.urls.experiment')),

	url(r'^projects?/', include('experimentdb.projects.urls.project')),
	url(r'^subprojects?/', include('experimentdb.projects.urls.subproject')),

	url(r'^hypotheses/', include('experimentdb.hypotheses.urls.hypotheses')),
	url(r'^process/', include('experimentdb.hypotheses.urls.process')),
	url(r'^manipulation/', include('experimentdb.hypotheses.urls.manipulation')),    

	(r'^proteins?/', include('experimentdb.proteins.urls')),

	url(r'^reagents?/$', 'experimentdb.reagents.views.index', name="reagent-list"),

	url(r'^protocols?/', include('experimentdb.data.urls.protocol')),
	url(r'^protocols?/$', 'experimentdb.data.views.protocol_list'),
	url(r'^protocols?/(?P<protocol_slug>[-\w\d]+)/$', 'experimentdb.data.views.protocol_detail'),
	url(r'^sgd/(?P<gene>[-\w\d]+)/$', 'experimentdb.datasets.views.sgd_gene_detail', name="sgd-gene-detail"),

	url(r'^constructs?/', include('experimentdb.reagents.urls.construct')),
	url(r'^vectors?/', include('experimentdb.reagents.urls.construct')),
	url(r'^plasmids?/', include('experimentdb.reagents.urls.construct')),
	url(r'^recombinant-?dna/', include('experimentdb.reagents.urls.construct')),

	url(r'^antibodys?/', include('experimentdb.reagents.urls.antibody')),
	url(r'^antibodies?/', include('experimentdb.reagents.urls.antibody')),

	url(r'^primers?/', include('experimentdb.reagents.urls.primer')),

	url(r'^cells?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cell-?lines?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cultured-cell-?lines?/', include('experimentdb.reagents.urls.cell')),

	url(r'^chemicals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^drugs?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^pharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^biopharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	
	url(r'^strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeast_?strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeasts?/', include('experimentdb.reagents.urls.strain')),
    
    url(r'^licenses?/', include('experimentdb.reagents.urls.license')),
    url(r'^mtas?/', include('experimentdb.reagents.urls.license')),
	
	(r'^clones?/', include('experimentdb.cloning.urls')),
	(r'^clonings?/', include('experimentdb.cloning.urls')),
	
	(r'^shipments?/', include('experimentdb.sharing.urls')),
	(r'^sharings?/', include('experimentdb.sharing.urls')),
	(r'^sent_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped?/', include('experimentdb.sharing.urls')),

        (r'^vendors?/', include('experimentdb.external.urls.vendor')),
        (r'^company/', include('experimentdb.external.urls.vendor')),
        (r'^companies/', include('experimentdb.external.urls.vendor')),
        (r'^contacts?/', include('experimentdb.external.urls.contact')),
        (r'^references?/', include('experimentdb.external.urls.reference')),
	

	(r'^pi35p2bp/$', 'django.views.generic.list_detail.object_list', {
		"queryset": PI35P2_Binding_Screen_SP.objects.all(),
		'template_name': 'gene_list.html',
		}),
	)

hypotheses/models.py
"""
The this file controls the data models in the hypotheses application.

The purpose of this app is to organize results and observations or summaries of experimental hypotheses in a systematic way.  A hypothesis is something that is observed about a biological process or biological entity.  It is supported by evidence, which could be an external publication or an experiment contained in this database.  The goal is to be able to say "X causes Y in this context, with the following evidence" 

The hypothesis app has 7 data models:
* Hypothesis
* Manipulation
* Effect
* Process
* Entity
* Context
* Evidence 
* CitationType
"""

from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from experimentdb.reagents.models import Primer, Construct, Chemical, Species, Cell, Strain
from experimentdb.proteins.models import Protein
from experimentdb.data.models import Protocol, Experiment
from experimentdb.external.models import Contact, Reference


MANIPULATION_TYPE = (
	('Treatment', 'Treatment'),
	('Overexpression', 'Overexpression'),
	('Knockdown', 'Knockdown'),
	('Knockout', 'Knockout'),
)

CONTEXT_TYPE = (
	('Species', 'Species'),
	('Tissues', 'Tissues'),
	('Cells', 'Cells'),
	('Sub-Cellular Location', 'Sub-Cellular Location'),
	('Multi-Protein Complex', 'Multi-Protein Complex'),
)

EVIDENCE_TYPE = (
	('Publication', 'Publication'),
	('Experiment', 'Experiment'),
	('Un-Published Communication', 'Un-Published Communication'),
	('Presentation', 'Presentation'),
    ('Figure','Figure')
)

CITATION_GROUP = (
    ('Positive', 'Positive'),
    ('Negative', 'Negative'),
    ('Neutral', 'Neutral'),
    ('No Opinion', 'No Opinion')
)

class Hypothesis(models.Model):
    """This model is the main model for this app, defining the particular hypothesis under consideration.

    This app has many to many field links to Manipulation, Context and Evidence and a ForeignKey link to an Effect and either a Process or Entity.  The required fields are manipulation, effect and either a process or entity.  The unicode representation of this model is going to be "(manipulation) (effects)/(process or entity in which there could be several).  The absolute url for an instance is /experimentdb/hypothesis/# where # is the primary key.  Tests are generated to test model formation with required and all fields, as well as to test the clean and absolute_url.  
    """
    cause_process = models.ForeignKey('Process', 
        blank=True, null=True, 
        verbose_name="Causative Process", 
        related_name = "cause_process",
        help_text="A biological process such as glucose uptake or endocytosis.  Select either an entity or a process but not both")	
    cause_entity = models.ForeignKey('Entity', 
        blank=True, null=True, 
        verbose_name="Causative Protein or Chemical",
        related_name = "cause_entity",
        help_text="A particular biological entity such as a protein or phosphorylation site.  Select either an entity or a process but not both.")	
    manipulation = models.ForeignKey('Manipulation', 
        blank=True, null=True, 
        help_text="Experimental Details")
    effect = models.ForeignKey('Effect')
    process = models.ForeignKey('Process', 
        blank=True, null=True, 
        verbose_name = "Affected Process",
        related_name = "affected_process",
        help_text="A biological process such as glucose uptake or endocytosis.  Select either an entity or a process but not both")	
    entity = models.ForeignKey('Entity', 
        blank=True, null=True, 
        related_name = "affected_entity",
        verbose_name = "Affected Thing",
        help_text="A particular biological entity such as a protein or phosphorylation site.  Select either an entity or a process but not both.")
    context = models.ForeignKey('Context', 
        blank=True, null=True, 
        help_text="Describes the model system and potential restrictions.  Since only one context might be selected, the context may need to be quite specific.")	
    evidence = models.ManyToManyField('Evidence', blank=True, null=True)
    identical_hypotheses = models.ManyToManyField("self", blank=True, null=True, help_text="Some processes or entities may generally correlate.  As an example, the process activation of mTORC1 generally correlates wth activation of pThr 389 phosphorylation.  In these cases, both hypotheses are symmetrically linked.")
    create_date = models.DateField(auto_now_add = True)
    modified_date = models.DateField(auto_now = True)

    def clean(self):
        """This validates that either a process or an entity (but not both) are selected."""
        if self.process and self.entity:
            raise ValidationError('Choose either a process or an entity but not both.')
        if self.process == None and self.entity == None:
            raise ValidationError('Choose a process or entity')		
	
    def __unicode__(self):
        """The unicode string for this model will show entity of entity is present and process if process is present.  The over-riding of clean should ensure that only one of the two is present."""
        if self.process and self.context and self.manipulation:
            return u'%s %s %s in %s' % (self.manipulation, self.effect, self.process, self.context)
        elif self.process and self.manipulation:
            return u'%s %s %s' % (self.manipulation, self.effect, self.process)
        elif self.entity and self.context and self.manipulation:
            return u'%s %s %s in %s' % (self.manipulation, self.effect, self.entity, self.context)
        elif self.entity and self.manipulation:
            return u'%s %s %s' % (self.manipulation, self.effect, self.entity)
        elif self.cause_entity and self.process and self.context:
            return u'%s %s %s in %s' % (self.cause_entity, self.effect, self.process, self.context)
        elif self.cause_process and self.process and self.context:
            return u'%s %s %s in %s' % (self.cause_process, self.effect, self.process, self.context) 
        elif self.cause_entity and self.process:
            return u'%s %s %s' % (self.cause_entity, self.effect, self.process)
        elif self.cause_process and self.process:
            return u'%s %s %s' % (self.cause_process, self.effect, self.process)             
        else:
            return "Unspecified Hypothesis"
			
    @models.permalink
    def get_absolute_url(self):
        return ('hypothesis-detail', [str(self.id)])			

    class Meta:
        verbose_name_plural = 'hypotheses'			

	
class Manipulation(models.Model):
    """This model defines particular manipulations of experimental systems.
	
	This Manipulation or (treatment), could be several things.  It may refer to the manipulation of a protein.  This could be a knockout of a gene/knockdown with a siRNA, overexpression with a construct, or treatment with a chemical or another protein.  The required fields are type plus the appropriate chemical, protein_added or protien.  There are optional fields for manipulation time and concentration (if needed).  There are validators to validate each type.  The unicode representation of a manipulation is "something - type" depending on the type.
    """
    type = models.CharField(max_length=25, choices=MANIPULATION_TYPE)
    time = models.TimeField(blank=True, null=True, help_text = "Enter if an incubation time is relevant.  Use format hour,min,sec with min and sec")
    concentration = models.CharField(max_length=25, blank=True, null=True, help_text = "Enter if a particular concentration or amount of chemical/protein is used")
    chemical = models.ForeignKey(Chemical, blank=True, null=True, help_text="Enter a chemical or a protein_added when type is treatment")
    protein_added = models.ForeignKey(Protein, blank=True, null=True, related_name="stimulating_protein", help_text="Use this or chemical when type is treatment.  This refers to a stimulating protein, not a protein being tested")	
    protein = models.ForeignKey(Protein, blank=True, null=True, related_name="target_protein", help_text="Select the target of the knockdown/knockout/inhibition/overexpression.")
	
    def clean(self):
        """This validates that a treatment has a chemical or a protein_added."""
        if self.type == "Treatment" and self.chemical == None and self.protein_added == None:
            raise ValidationError('Choose either a chemical or protein for a treatment.')	
        """This validates that an overexpression has a construct."""
        if self.type == "Overexpression" and self.protein == None:
            raise ValidationError('Choose an overexpressed protein')
        """This validates that a knockdown has a protein target."""
        if self.type == "Knockdown" and self.protein == None:
            raise ValidationError('Choose a protein which is knocked down.')
        """This validates that a knockout has a protein target.""" 
        if self.type == "Knockout"	and self.protein == None:
            raise ValidationError('Choose a protein which is knocked out')

			
    def __unicode__(self):
        """The unicode representation depends on the type of manipulation."""	
        if self.type == "Treatment" and self.chemical and self.protein_added:
            return u'%s and %s %s' % (self.chemical, self.protein_added, self.type)
        elif self.type == "Treatment" and self.chemical:
            return u'%s %s' % (self.chemical, self.type)
        elif self.type == "Treatment" and self.protein_added:
            return u'%s %s' % (self.protein_added, self.type)
        else:
            return u'%s %s' % (self.protein, self.type)
            
    @models.permalink
    def get_absolute_url(self):

hypotheses/views.py
### This module describes the views for the hypotheses app"""

hypotheses/templates/context_detail.html
{% extends "base.html" %}

{% block head_title %}Context Detail - {{ object }}{% endblock %}
{% block title %}Context Detail - {{ object }}{% endblock %}
{% block content %}
<h2>{{ object }}</h2>
{% endblock %}

hypotheses/templates/context_form.html
{% extends "base.html" %}

{% block head_title %}{% if object %}Update Context {{object}}{% else %} New Context {% endif %}{% endblock %}
{% block title %}{% if object %}Update Context {{object}}{% else %} New Context {% endif %}{% endblock %}
{% block scripts %}
{% endblock %}
{% block content %}
<form method="POST" action=".">
<table>{{ form }}</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}

hypotheses/templates/context_list.html
{% extends "base.html" %}
{% block scripts %}
{% include "sortable_table_script.html" %}
{% endblock scripts %}
{% block head_title %}Context List{% endblock %}
{% block title %}Context List{% endblock %}
{% block content %}

<tbody>
	<th>Context</th>
{% for context in object_list %}
<tr>
	<td><a href="{{context.get_absolute_url}}">{{context }}</a></td>
	<td>
		<a href="{% url context-detail context.id %}"><img src="{{STATIC_URL}}img/icons/Zoom.png" width=25 alt="Detail"></a>
	{% if perms.hypothesis.change_context %}
		<a href="{% url hypothesis-edit context.id %}"><img src="{{STATIC_URL}}img/icons/Document Write.png" width=25 alt="Edit"></a>
	{% endif %}
	{% if perms.hypothesis.delete_context	%}
		<a href="{% url hypothesis-delete context.id %}"><img src="{{STATIC_URL}}img/icons/Close.png" width=25 alt="delete></a>
	{% endif %}
	</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

hypotheses/templates/entity_form.html
{% extends "base.html" %}

{% block head_title %}{% if object %}Update Entity {{object}}{% else %} New Entity {% endif %}{% endblock %}
{% block title %}{% if object %}Update Entity {{object}}{% else %} New Entity {% endif %}{% endblock %}
{% block scripts %}
{% endblock %}
{% block content %}
<form method="POST" action=".">
<table>{{ form }}</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}

hypotheses/templates/entity_list.html
{% extends "base.html" %}
{% block scripts %}
{% include "sortable_table_script.html" %}
{% endblock scripts %}
{% block head_title %}Entity List{% endblock %}
{% block title %}Entity List{% endblock %}
{% block content %}

<tbody>
	<th>Entity</th>
{% for entity in object_list %}
<tr>
	<td><a href="{{entity.get_absolute_url}}">{{entity }}</a></td>
	<td>
		<a href="{% url entity-detail entity.id %}"><img src="{{STATIC_URL}}img/icons/Zoom.png" width=25 alt="Detail"></a>
	{% if perms.hypothesis.change_entity %}
		<a href="{% url entity-edit entity.id %}"><img src="{{STATIC_URL}}img/icons/Document Write.png" width=25 alt="Edit"></a>
	{% endif %}
	{% if perms.hypothesis.delete_entity %}
		<a href="{% url entity-delete entity.id %}"><img src="{{STATIC_URL}}img/icons/Close.png" width=25 alt="delete></a>
	{% endif %}
	</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

hypotheses/templates/evidence_detail.html
{% extends "base.html" %}

{% block head_title %}Evidence Detail - {{ object }}{% endblock %}
{% block title %}Evidence Detail - {{ object }}{% endblock %}
{% block content %}
<h2>{{ object }}</h2>
{% endblock %}

hypotheses/templates/evidence_list.html
{% extends "base.html" %}
{% block scripts %}
{% include "sortable_table_script.html" %}
{% endblock scripts %}
{% block head_title %}Evidence List{% endblock %}
{% block title %}Evidence List{% endblock %}
{% block content %}

<tbody>
	<th>Evidence</th>
{% for evidence in object_list %}
<tr>
	<td><a href="{{evidence.get_absolute_url}}">{{evidence }}</a></td>
	<td>
		<a href="{% url evidence-detail evidence.id %}"><img src="{{STATIC_URL}}img/icons/Zoom.png" width=25 alt="Detail"></a>
	{% if perms.hypothesis.change_evidence %}
		<a href="{% url evidence-edit evidence.id %}"><img src="{{STATIC_URL}}img/icons/Document Write.png" width=25 alt="Edit"></a>
	{% endif %}
	{% if perms.hypothesis.delete_evidence %}
		<a href="{% url evidence-delete evidence.id %}"><img src="{{STATIC_URL}}img/icons/Close.png" width=25 alt="delete></a>
	{% endif %}
	</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

hypotheses/templates/hypothesis_detail.html
{% extends "base.html" %}

{% block head_title %}Hypothesis Detail - {{ object }}{% endblock %}
{% block title %}Hypothesis Detail - {{ object }}{% endblock %}
{% block content %}
<h2>{{ object }}</h2>
<table>
	<tr>
		<th>Start</th>
		<td>{{ object.create_date }}</td>
	</tr>
	<tr>
		<th>Updated</th>
		<td>{{ object.update_date }}</td>
	</tr>
	<tr>
		<th>Manipulation</th>
		<td><a href="{{ object.manipulation.get_absolute_url }}">{{ object.manipulation }}</a></td>
	</tr>    
	<tr>
		<th>Effect</th>
		<td>{{ object.effect }}</td>
	</tr>
{% if object.process %}   
	<tr>
		<th>Process</th>
		<td><a href="{{ object.process.get_absolute_url }}">{{ object.process }}</a></td>
	</tr>
{% endif %}
{% if object.entity %}   
	<tr>
		<th>Entity</th>
		<td><a href="{{ object.entity.get_absolute_url }}">{{ object.entity }}</a></td>
	</tr>
{% endif %} 
{% if object.context %}   
	<tr>
		<th>Context</th>
		<td><a href="{{ object.context.get_absolute_url }}">{{ object.context }}</a></td>
	</tr>
{% endif %} 
{% if object.identical_hypotheses.count > 0 %}   
	<tr>
		<th>Identical Hypotheses</th>
		<td><ul>{% for hypothesis in object.identical_hypotheses.all %}
        <li><a href="{{ hypothesis.get_absolute_url }}">{{ hypothesis }}</a></li>
        {% endfor %}</ul></td>
	</tr>
{% endif %}      
</table>
<h3>Evidence</h3>
{% for evidence in object.evidence.all %}<li><a href="{{ evidence.get_absolute_url }}">{{ evidence }}</a> ({{ evidence.citation_type }})</li>{% endfor %}
{% endblock %}

hypotheses/templates/hypothesis_form.html
{% extends "base.html" %}

{% block head_title %}{% if object %}Update Hypothesis {{object}}{% else %} New Hypothesis {% endif %}{% endblock %}
{% block title %}{% if object %}Update Hypothesis {{object}}{% else %} New Hypothesis {% endif %}{% endblock %}
{% block scripts %}
{% endblock %}
{% block content %}
<form method="POST" action=".">
<table>{{ form }}</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}

hypotheses/templates/hypothesis_list.html
{% extends "base.html" %}
{% block scripts %}
{% include "sortable_table_script.html" %}
{% endblock scripts %}
{% block head_title %}Hypothesis List{% endblock %}
{% block title %}Hypothesis List{% endblock %}
{% block content %}
{% with object_list as hypothesis_list %}
{% include "hypothesis_table.html" %}
{% endwith %}
{% endblock %}

hypotheses/templates/hypothesis_table.html
<table>
<tbody>
	<tr><th>Hypothesis</th></tr>
{% for hypothesis in hypothesis_list %}
<tr>
	<td><a href="{{hypothesis.get_absolute_url}}">{{hypothesis }}</a></td>
	<td>
		<a href="{% url hypothesis-detail hypothesis.id %}"><img src="{{STATIC_URL}}img/icons/Zoom.png" width=25 alt="Detail"></a>
	{% if perms.hypothesis.change_hypothesis %}
		<a href="{% url hypothesis-edit hypothesis.id %}"><img src="{{STATIC_URL}}img/icons/Document Write.png" width=25 alt="Edit"></a>
	{% endif %}
	{% if perms.hypothesis.delete_hypothesis %}
		<a href="{% url hypothesis-delete hypothesis.id %}"><img src="{{STATIC_URL}}img/icons/Close.png" width=25 alt=delete></a>
	{% endif %}
	</td>
</tr>
{% endfor %}
</tbody>
</table>

hypotheses/templates/manipulation_detail.html
{% extends "base.html" %}

{% block head_title %}Manipulation Detail - {{ object }}{% endblock %}
{% block title %}Manipulation Detail - {{ object }}{% endblock %}
{% block content %}
<h2>{{ object }}</h2>
<div class="fg-buttonset">
{% if perms.hypotheses.create_manipulation %}
<a href="{% url manipulation-new %}"><button class="fg-button ui-state-default ui-corner-left"><span class="ui-icon ui-icon-circle-plus"></span>Add New Manipulation</button></a>
{% endif %}
{% if perms.hypotheses.change_manipulation %}
<a href="{% url manipulation-edit object.id %}"><button class="fg-button ui-state-default"><span class="ui-icon ui-icon-pencil"></span>Edit</button></a>
{% endif %}
{% if perms.hypotheses.delete_manipulation %}
<a href="{% url manipulation-delete object.id %}"><button class="fg-button ui-state-default ui-corner-right"><span class="ui-icon ui-icon-trash"></span>Delete</button></a>
{% endif %}
</div>
<table>
    <tr><th>Type</th><td>{{object.type}}</td>
    {% if object.time %}<tr><th>Time</th><td>{{object.time}}</td>{% endif %}
    {% if object.concentration %}<tr><th>Concentration</th><td>{{object.concentration}}</td>{% endif %}
    {% if object.chemical %}<tr><th>Chemical</th><td><a href="{{object.chemical.get_absolute_url}}">{{object.chemical}}</a></td>{% endif %}    
    {% if object.protein_added %}<tr><th>Protein Added</th><td><a href="{{object.protein_added.get_absolute_url}}">{{object.protein_added}}</a></td>{% endif %}
    {% if object.protein %}<tr><th>Target Protein</th><td><a href="{{object.protein.get_absolute_url}}">{{object.protein}}</a></td>{% endif %}    
</table>

<div id="hypotheses" class="grid_12">
<h2>Tested Hypotheses</h2>
{% with object.hypothesis_set.all as hypothesis_list %}
{% include "hypothesis_table.html" %}
{% endwith %}

{% endblock %}

hypotheses/templates/manipulation_list.html
{% extends "base.html" %}
{% block scripts %}
{% include "sortable_table_script.html" %}
{% endblock scripts %}
{% block head_title %}Manipulation List{% endblock %}
{% block title %}Manipulation List{% endblock %}
{% block content %}

<tbody>
	<th>Manipultion</th>
{% for manipulation in object_list %}
<tr>
	<td><a href="{{manipulation.get_absolute_url}}">{{manipulation }}</a></td>
	<td>
		<a href="{% url manipulation-detail manipulation.id %}"><img src="{{STATIC_URL}}img/icons/Zoom.png" width=25 alt="Detail"></a>
	{% if perms.hypothesis.change_manipulation %}
		<a href="{% url manipulation-edit manipulation.id %}"><img src="{{STATIC_URL}}img/icons/Document Write.png" width=25 alt="Edit"></a>
	{% endif %}
	{% if perms.hypothesis.delete_manipulation %}
		<a href="{% url manipulation-delete manipulation.id %}"><img src="{{STATIC_URL}}img/icons/Close.png" width=25 alt="delete></a>
	{% endif %}
	</td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

hypotheses/templates/process_form.html
{% extends "base.html" %}

{% block head_title %}{% if object %}Update Process {{object}}{% else %} New Process {% endif %}{% endblock %}
{% block title %}{% if object %}Update Process {{object}}{% else %} New Process {% endif %}{% endblock %}
{% block scripts %}
{% endblock %}
{% block content %}
<form method="POST" action=".">
<table>{{ form }}</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}