urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
from experimentdb.datasets.models import SGD_GeneNames, SGD_phenotypes, PI35P2_Binding_Screen_SP

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^accounts/login/', 'django.contrib.auth.views.login'),
	(r'^comments?/', include('django.contrib.comments.urls')),
	(r'^search/$', 'experimentdb.views.search'),
	(r'^ajax_select/', include('ajax_select.urls')),
	(r'^add/protein_family/?$', 'experimentdb.proteins.views.newProteinFamily'),

	(r'^experiments?/', include('experimentdb.data.urls.experiment')),
	(r'^exps?/', include('experimentdb.data.urls.experiment')),

	url(r'^projects?/', include('experimentdb.projects.urls.project')),
	url(r'^subprojects?/', include('experimentdb.projects.urls.subproject')),

	url(r'^hypotheses/', include('experimentdb.hypotheses.urls.hypotheses')),
	url(r'^process/', include('experimentdb.hypotheses.urls.process')),
	url(r'^manipulation/', include('experimentdb.hypotheses.urls.manipulation')),    

	(r'^proteins?/', include('experimentdb.proteins.urls')),

	url(r'^reagents?/$', 'experimentdb.reagents.views.index', name="reagent-list"),

	url(r'^protocols?/', include('experimentdb.data.urls.protocol')),
	url(r'^protocols?/$', 'experimentdb.data.views.protocol_list'),
	url(r'^protocols?/(?P<protocol_slug>[-\w\d]+)/$', 'experimentdb.data.views.protocol_detail'),
	url(r'^sgd/(?P<gene>[-\w\d]+)/$', 'experimentdb.datasets.views.sgd_gene_detail', name="sgd-gene-detail"),

	url(r'^constructs?/', include('experimentdb.reagents.urls.construct')),
	url(r'^vectors?/', include('experimentdb.reagents.urls.construct')),
	url(r'^plasmids?/', include('experimentdb.reagents.urls.construct')),
	url(r'^recombinant-?dna/', include('experimentdb.reagents.urls.construct')),

	url(r'^antibodys?/', include('experimentdb.reagents.urls.antibody')),
	url(r'^antibodies?/', include('experimentdb.reagents.urls.antibody')),

	url(r'^primers?/', include('experimentdb.reagents.urls.primer')),

	url(r'^cells?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cell-?lines?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cultured-cell-?lines?/', include('experimentdb.reagents.urls.cell')),

	url(r'^chemicals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^drugs?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^pharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^biopharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	
	url(r'^strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeast_?strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeasts?/', include('experimentdb.reagents.urls.strain')),
    
    url(r'^licenses?/', include('experimentdb.reagents.urls.license')),
    url(r'^mtas?/', include('experimentdb.reagents.urls.license')),
	
	(r'^clones?/', include('experimentdb.cloning.urls')),
	(r'^clonings?/', include('experimentdb.cloning.urls')),
	
	(r'^shipments?/', include('experimentdb.sharing.urls')),
	(r'^sharings?/', include('experimentdb.sharing.urls')),
	(r'^sent_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped?/', include('experimentdb.sharing.urls')),

        (r'^vendors?/', include('experimentdb.external.urls.vendor')),
        (r'^company/', include('experimentdb.external.urls.vendor')),
        (r'^companies/', include('experimentdb.external.urls.vendor')),
        (r'^contacts?/', include('experimentdb.external.urls.contact')),
        (r'^references?/', include('experimentdb.external.urls.reference')),
	

	(r'^pi35p2bp/$', 'django.views.generic.list_detail.object_list', {
		"queryset": PI35P2_Binding_Screen_SP.objects.all(),
		'template_name': 'gene_list.html',
		}),
	)

data/models.py
from django.db import models

from experimentdb.projects.models import Project, SubProject
from experimentdb.proteins.models import Protein
from experimentdb.reagents.models import Construct, Antibody, Cell, Primer, Chemical, Strain, AnimalStrain
from experimentdb.external.models import Contact, Reference

class Protocol(models.Model):
    """Describes the protocol or protocols used to perform each experiment.  
    
    This model stores information about the protocol used for an experiment.    

    An experiment may have several protocols attached to it.  For example, one could culture and transfect cells, then generate lysates then do some western blots.
    
    Since migrating to a mediawiki based protocol storage system, the wiki_page attribute indicates the protocol wiki page.  In this model, the **protocol_revision** attribute indicates the particular revision of the protocol used for that particular experiment.  In this way a permalink can be generated to the specific protocol used for a particular experiment.  To find the protocol revision number, mouse over the permanent link on the protocol and record the number at the end of the url.
    """
       
    protocol = models.CharField(max_length=50)
    protocol_slug = models.SlugField(max_length=25)
    #reference = models.ManyToManyField(Reference, blank=True)
    protocol_file = models.FileField(upload_to='protocol', blank=True)
    protocol_revision = models.IntegerField(blank=True, null=True, help_text="ProtocolWiki page revision number")
    wiki_page = models.CharField(max_length=75, blank=True, help_text="ProtocolWiki page (via MediaWiki)")
    comments = models.TextField(max_length=500, blank=True)	
    public = models.BooleanField()
    published = models.BooleanField()
    inactive = models.BooleanField()
    def __unicode__(self):
        return u'%s ' % self.protocol
    def get_absolute_url(self):
        return "/experimentdb/protocol/%i/" % self.id
	class Meta:
		ordering = ['-protocol']


class Experiment(models.Model):
    """Experiment objects are the central objects of this database.
    
    Experiment objects contain all details about an experiment including reagents, parameters, notes, results and data."""
    project = models.ManyToManyField(Project, blank=True, null=True)
    subproject = models.ManyToManyField(SubProject, blank=True, null=True)
    experimentID = models.SlugField(max_length=50, help_text="ie DB-2008-11-11-A", primary_key=True)
    experiment = models.CharField(max_length=100)
    protocol = models.ManyToManyField(Protocol, blank=True, null=True)
    assay = models.CharField(max_length=100, blank=True, null=True)
    experiment_date = models.DateField(help_text="Date Performed")
    cellline = models.ManyToManyField(Cell, blank=True, null=True)
    antibodies = models.ManyToManyField(Antibody, blank=True, null=True)
    chemicals = models.ManyToManyField(Chemical, blank=True, null=True)
    constructs = models.ManyToManyField(Construct, blank=True, null=True)
    siRNA = models.ManyToManyField(Primer, blank=True, null=True, limit_choices_to = {'primer_type': 'siRNA'})
    strain = models.ManyToManyField(Strain, blank=True, null=True)
    animal_model = models.ManyToManyField(AnimalStrain, blank=True, null=True)
    animal_cohort = models.ManyToManyField('AnimalCohort', blank=True, null=True)
    comments = models.TextField(max_length=500, blank=True, null=True)
    researcher = models.ManyToManyField(Contact, blank=True, null=True)
    protein = models.ManyToManyField(Protein, blank=True, null=True)
    public = models.BooleanField()
    published = models.BooleanField()
    sample_storage = models.CharField(max_length=100, blank=True)
    def __unicode__(self):
        """The unicode representation of an experiment object is the experiment on assay; date."""
        return u'%s on %s; %s' % (self.experiment, self.assay, self.experiment_date)
    def get_absolute_url(self):
        """The default url for an experiment is /experimentdb/experiment/experimentID."""
        return "/experimentdb/experiment/%s/" % self.experimentID
    class Meta:
        """The default ordering for experiments is in reverse of the experiment_date."""
        ordering = ['-experiment_date']

class Result(models.Model):
	experiment = models.ForeignKey(Experiment)
	conclusions = models.TextField(max_length=500, blank=True)
	#datafile = models.MultiFileField(upload_to='raw/%Y/%m/%d', blank=True)	
	file1 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	file2 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	file3 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan1 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan2 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan3 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan4 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan5 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	result_figure1 = models.ImageField(upload_to='final/%Y/%m/%d', blank=True)
	result_figure2 = models.ImageField(upload_to='final/%Y/%m/%d', blank=True)
	public = models.BooleanField()
	published = models.BooleanField()
	def __unicode__(self):
		return u'%s ' % self.experiment
	def get_absolute_url(self):
		return "/result/%i/" % self.id


class Sequencing(models.Model):
	clone_name = models.CharField(max_length=15)
	construct = models.ForeignKey(Construct)
	primer = models.ForeignKey(Primer)
	file = models.FileField(upload_to='sequencing/%Y/%m/%d', blank=True)
	sequence = models.CharField(max_length=1500)
	correct = models.BooleanField()
	notes = models.TextField(max_length=250,blank=True)
	date = models.DateField(blank=True)
	sample_number = models.IntegerField(max_length=8, blank=True, null=True)
	gel_number = models.IntegerField(max_length=8, blank=True, null=True)
	lane_number = models.IntegerField(max_length=3, blank=True, null=True)
	def __unicode__(self):
		return u'%s-%s' % (self.construct,self.clone_name)
        
class AnimalCohort(models.Model):

    """This model describes a particular cohort of animals.  
    
    As an example, an experiment might be dont with a particular knockout model, over several cohorts.
    This model defines two required classes, name and a many to many field for  :class:`~experimentdb.reagents.models.AnimalStrain`, and optional notes, start and end dates.
    The unicode name of this is "name" field and the url is /cohort/id where id is the primary key."""
    name = models.CharField(max_length=50)
    animal_model = models.ManyToManyField(AnimalStrain)
    date_start = models.DateField(blank=True, null=True, help_text="Cohort Start Date")
    date_end = models.DateField(blank=True, null=True, help_text="Cohort End Date")
    notes = models.TextField(blank=True, null=True)
    def __unicode__(self):
        return u'%s' % (self.name) 
    def get_absolute_url(self):
        return "/cohort/%i/" % self.id        

projects/models.py
"""This package describes the schema for the projects app.

The two models are for projects and subprojects, with the latter having a foreignkey to the former."""

from django.db import models
from django.template.defaultfilters import slugify

from experimentdb.external.models import Contact, Reference

class Project(models.Model):
    """This defines the major project model.

    Projects are thought of as large, grant sized groups of data, whereas subprojects are paper sized projects, attached to a main project."""
    project = models.CharField(max_length=50)
    project_slug = models.SlugField(max_length=15, primary_key=True) #this field is slugified on save
    comments = models.TextField(max_length=250, blank=True, null=True)
    public = models.BooleanField()
    published = models.BooleanField()
    collaborators = models.ManyToManyField(Contact, blank=True, null=True)
    papers = models.ManyToManyField(Reference, blank=True, null=True)

    def __unicode__(self):
        return u'%s ' % self.project

    @models.permalink
    def get_absolute_url(self):
        return ('project-detail', [str(self.project_slug)])

    #def save(self):
     #   """The save is over-ridden to slugify the project field into a slugfield."""
     #   self.project_slug = slugify( self.project )
      #  super( Project, self ).save()



class SubProject(models.Model):
    """This model defines a subproject.

    These projects are generally offshoots of major projectsand are paper or thesis sized projects."""
    project = models.ForeignKey(Project)
    subproject = models.CharField(max_length=50)
    project_slug = models.SlugField(max_length=15, primary_key=True) #this field is slugified on save
    comments = models.TextField(max_length=250, blank=True, null=True)
    public = models.BooleanField()
    published = models.BooleanField()
    collaborators = models.ManyToManyField(Contact, blank=True, null=True)
    papers = models.ManyToManyField(Reference, blank=True, null=True)

    class Meta:
        verbose_name_plural = "Sub-Projects"
        verbose_name = "Sub-Project"

    def __unicode__(self):
        return u'%s ' % self.subproject

    @models.permalink
    def get_absolute_url(self):
        return ('subproject-detail', [str(self.project_slug)])

    def save(self):
        """The save is over-ridden to slugify the subproject field into a slugfield."""
        self.subproject_slug = slugify( self.project )
        super( SubProject, self ).save()

projects/templates/detail.html
{% extends "base.html" %}

{% block title %} Project Detail {% endblock %}
{% block content %}
<h2>{{ project.project }}</h2>
<p>{{ project.comments }}</p>
{% for subproject in proj_subproject %}
<h3>SubProject: <a href="/experimentdb/subproject/{{ subproject.project_slug }}">{{ subproject.subproject }}</a></h3>
<p>{{ subproject.comments }}</p>
{% endfor %}
<h3>Experiments</h3>
<ul>{% for experiment in proj_experiment %}
<li><a href="/experimentdb/experiment/{{experiment.experimentID}}">{{ experiment }}</a>
{% endfor %}
</ul>
{% endblock %}

projects/templates/detail_sub.html
{% extends "base.html" %}

{% block title %} SubProject Detail {% endblock %}
{% block content %}
<h2>{{ subproject.subproject }}</h2>
<p>{{ subproject.comments }}</p>
<h3>Experiments</h3>
<ul>{% for experiment in proj_experiment %}
<li><a href="/experimentdb/experiment/{{experiment.experimentID}}">{{ experiment }}</a>
{% endfor %}
</ul>
{% endblock %}

projects/templates/index.html
{% extends "base.html" %}

{% block head_title %}Project List{% endblock %}
{% block title %}Project List{% endblock %}
{% block content %}
{% for project in project_list %}
<h2><a href="/experimentdb/project/{{ project.project_slug }}"> {{ project.project }}.</a></h2>
<p>{{ project.comments }}</p>
{% endfor %}
{% endblock %}

projects/templates/project_detail.html
{% extends "base.html" %}
{% block head_title %} {{project}} Project Detail {% endblock %}
{% block title %} Project Detail {% endblock %}
{% block content %}
<div id="project" class="grid_5">
<h1>{{ project }}</h1>
<p>{{ project.comments }}</p>
</div>
<div id="subprojects" class="grid_5">
{% for subproject in project.subproject_set.all %}
<h3>SubProject: <a href="{{ subproject.get_absolute_url }}">{{ subproject.subproject }}</a></h3>
<p>{{ subproject.comments }}</p>
{% endfor %}
</div>
<div = "experiments" class="grid_12">
{% with project.experiment_set.all as experiment_list %}
{% include "experiment_list_table.html" %}
{% endwith %}
</div>
<<hr>
{% with project as object %}
{% include "comment.html" %}
{% endwith %}
{% endblock %}

projects/templates/project_detail_sub.html
{% extends "base.html" %}
{% block head_title %} {{ subproject }} Project Detail {% endblock %}
{% block title %} SubProject Detail {% endblock %}
{% block content %}
<div id="subproject" class="grid_12">
<h1>{{ subproject.subproject }}</h1>
<p>{{ subproject.comments }}</p>
</div>
<div id="experiments" class="grid_12">
{% with subproject.experiment_set.all as experiment_list %}
{% include "experiment_list_table.html" %}
{% endwith %}
</div>
{% with subproject as object %}
{% include "comment.html" %}
{% endwith %}
{% endblock %}

projects/templates/project_form.html
{% extends "base.html" %}

{% block head_title %}{% if object %}Update Project {{object}}{% else %} New Project {% endif %}{% endblock %}
{% block title %}{% if object %}Update Project {{object}}{% else %} New Project {% endif %}{% endblock %}
{% block content %}
<form method="post" {% if object %} action="{% url project-edit object.id %}"{% else %} action="{% url project-new %}"{% endif%}>{% csrf_token %}
<table>{{ form }}</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}

projects/templates/project_index.html
{% extends "base.html" %}

{% block head_title %}Project List{% endblock %}
{% block title %}Project List{% endblock %}
{% block content %}
<table>
<thead>
<tr>
 <th>Project</th>
 <th>Summary</th>
 <th>Experiments</th>
</tr>
</thead>
<tbody>
{% for project in project_list %}
<tr>
 <th><a href="{% url project-detail project.project_slug %}">{{ project }}</a></th>
 <td>{{ project.comments }}</td>
 <td>{{ project.experiment_set.count }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% if perms.reagents.add_antibody %}<p>Click <a href="{% url project-new %}"><img src="{{STATIC_URL}}img/icons/Add.png" width=25 alt="here"></a> for a new project.</p>{% endif %}
{% endblock %}

projects/templates/project_list.html
{% extends "base.html" %}

{% block head_title %}Project List{% endblock %}
{% block title %}Project List{% endblock %}
{% block content %}
<table>
<thead>
<tr>
 <th>Project</th>
 <th>Summary</th>
 <th>Experiments</th>
</tr>
</thead>
<tbody>
{% for project in project_list %}
<tr>
 <th><a href="{% url project-detail project.project_slug %}">{{ project }}</a></th>
 <td>{{ project.comments }}</td>
 <td>{{ project.experiment_set.count }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% if perms.projects.add_project %}<p>Click <a href="{% url project-new %}"><img src="{{STATIC_URL}}img/icons/Add.png" width=25 alt="here"></a> for a new project.</p>{% endif %}
{% endblock %}

projects/templates/subproject_detail.html
{% extends "base.html" %}
{% block head_title %} {{ subproject }} Project Detail {% endblock %}
{% block title %} SubProject Detail {% endblock %}
{% block content %}
<div id="subproject" class="grid_12">
<h1>{{ subproject.subproject }}</h1>
<p>{{ subproject.comments }}</p>
</div>
<div id="experiments" class="grid_12">
{% with subproject.experiment_set.all as experiment_list %}
{% include "experiment_list_table.html" %}
{% endwith %}
</div>
{% with subproject as object %}
{% include "comment.html" %}
{% endwith %}
{% endblock %}

projects/templates/subproject_form.html
{% extends "base.html" %}

{% block head_title %}{% if object %}Update Project {{object}}{% else %} New Project {% endif %}{% endblock %}
{% block title %}{% if object %}Update Project {{object}}{% else %} New Project {% endif %}{% endblock %}
{% block content %}
<form method="post" {% if object %} action="{% url subproject-edit object.id %}"{% else %} action="{% url subproject-new %}"{% endif%}>{% csrf_token %}
<table>{{ form }}</table>
<input type="submit" value="Submit" />
</form>
{% endblock %}

projects/templates/subproject_list.html
{% extends "base.html" %}

{% block head_title %}Sub-Project List{% endblock %}
{% block title %}Sub-Project List{% endblock %}
{% block content %}
<table>
<thead>
<tr>
 <th>Sub-Project</th>
 <th>Summary</th>
 <th>Experiments</th>
</tr>
</thead>
<tbody>
{% for subproject in subproject_list %}
<tr>
 <th><a href="{% url subproject-detail subproject.subproject_slug %}">{{ subproject }}</a></th>
 <td>{{ subproject.comments }}</td>
 <td>{{ subproject.experiment_set.count }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% if perms.projects.add_subproject %}<p>Click <a href="{% url subproject-new %}"><img src="{{STATIC_URL}}img/icons/Add.png" width=25 alt="here"></a> for a new subproject.</p>{% endif %}
{% endblock %}