proteins/urls.py
"""
This package defines url redirections for the proteins app.

This app takes a url request in the form of /experimentdb/protein/something and redirects to the following views:
* protein-list
* protein-detail
* protein-new
* protein-edit
* protein-delete
* protein-family-list
* protein-family-detail
* protein-family-new
* protein-detail-new
* protein-detail-edit
* protein-detail-delete
* protein-isoform-detail
* protein-name-slug
"""

from django.conf.urls.defaults import *
from django.views.generic.create_update import create_object, update_object, delete_object
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic.list_detail import object_list, object_detail

from experimentdb.proteins.forms import ProteinForm
from experimentdb.proteins.models import ProteinFamily, ProteinDetail, Protein

@login_required
def restricted_object_list(*args, **kwargs):
	return object_list(*args, **kwargs)

@login_required
def restricted_detail(*args, **kwargs):
	return object_detail(*args, **kwargs)

@permission_required('proteins.add_protein')
def restricted_create_protein(*args, **kwargs):
	return create_object(*args, **kwargs)

@permission_required('proteins.change_protein')
def restricted_change_protein(*args, **kwargs):
	return update_object(*args, **kwargs)

@permission_required('reagents.delete_protein')
def restricted_delete_protein(*args, **kwargs):
	return delete_object(*args, **kwargs)

urlpatterns = patterns('',
	url(r'^$', restricted_object_list, {
		"queryset": Protein.objects.all(), 
		'template_name': 'protein_list.html',
		'template_object_name':'protein',
		}, name='protein-list'),	
	url(r'(?P<object_id>[\d]+)/$', restricted_detail, {
		"queryset": Protein.objects.all(), 
		'template_object_name': 'protein',
		'template_name': 'protein_detail.html'
		,}, name='protein-detail'),
	url(r'^new/$', restricted_create_protein, {
		'form_class': ProteinForm, 
		'template_name': 'protein_form.html', 
		'login_required':True ,
		'post_save_redirect':"/experimentdb/protein"
		}, name='protein-new'),
	url(r'^(?P<object_id>[\d]+)/edit$', restricted_change_protein, {
		'model': Protein, 
		'template_name': 'protein_form.html',
		'login_required':True 
		,}, name="protein-edit"),
	url(r'^(?P<object_id>[\d]+)/delete$', restricted_delete_protein, {
		'model': Protein, 
		'login_required':True,
		'post_delete_redirect': '/experimentdb/protein'
		,}, name="protein-delete"),		
	url(r'^family/$', restricted_object_list, {
		"queryset": ProteinFamily.objects.all(), 
		'template_name': 'protein_family_list.html',
		}, name='protein-family-list'),
	url(r'^family/(?P<object_id>[\d]+)/$', restricted_detail, {
		"queryset": ProteinFamily.objects.all(), 
		'template_name': 'protein_family_detail.html'
		,}, name='protein-family-detail'),
	url(r'^family/new/$', restricted_create_protein, {
		'model': ProteinFamily, 
		'template_name': 'protein_family_form.html', 
		'login_required':True ,
		'post_save_redirect': "/experimentdb/protein/family"
		}, name='protein-family-new'),	
	url(r'^detail/new/$', restricted_create_protein, {
		'model': ProteinDetail, 
		'template_name': 'proteindetail_form.html', 
		'login_required':True
		}, name='protein-detail-new'),
	url(r'^detail/(?P<object_id>[\d]+)/edit$', restricted_change_protein, {
		'model': ProteinDetail, 
		'template_name': 'proteindetail_form.html',
		'login_required':True 
		,}, name="protein-detail-edit"),
	url(r'^detail/(?P<object_id>[\d]+)/delete$', restricted_delete_protein, {
		'model': ProteinDetail, 
		'login_required':True,
		'post_delete_redirect': '/experimentdb/protein'
		,}, name="protein-detail-delete"),			
	url(r'^(?P<protein_id>[\d]+)/$', 'experimentdb.proteins.views.protein_isoform_detail', name='protein-isoform-detail'),
	url(r'^(?P<protein>[-\w\d]+)/$', 'experimentdb.proteins.views.detail', name='protein-name-slug'),	
)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
from experimentdb.datasets.models import SGD_GeneNames, SGD_phenotypes, PI35P2_Binding_Screen_SP

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^accounts/login/', 'django.contrib.auth.views.login'),
	(r'^comments?/', include('django.contrib.comments.urls')),
	(r'^search/$', 'experimentdb.views.search'),
	(r'^ajax_select/', include('ajax_select.urls')),
	(r'^add/protein_family/?$', 'experimentdb.proteins.views.newProteinFamily'),

	(r'^experiments?/', include('experimentdb.data.urls.experiment')),
	(r'^exps?/', include('experimentdb.data.urls.experiment')),

	url(r'^projects?/', include('experimentdb.projects.urls.project')),
	url(r'^subprojects?/', include('experimentdb.projects.urls.subproject')),

	url(r'^hypotheses/', include('experimentdb.hypotheses.urls.hypotheses')),
	url(r'^process/', include('experimentdb.hypotheses.urls.process')),
	url(r'^manipulation/', include('experimentdb.hypotheses.urls.manipulation')),    

	(r'^proteins?/', include('experimentdb.proteins.urls')),

	url(r'^reagents?/$', 'experimentdb.reagents.views.index', name="reagent-list"),

	url(r'^protocols?/', include('experimentdb.data.urls.protocol')),
	url(r'^protocols?/$', 'experimentdb.data.views.protocol_list'),
	url(r'^protocols?/(?P<protocol_slug>[-\w\d]+)/$', 'experimentdb.data.views.protocol_detail'),
	url(r'^sgd/(?P<gene>[-\w\d]+)/$', 'experimentdb.datasets.views.sgd_gene_detail', name="sgd-gene-detail"),

	url(r'^constructs?/', include('experimentdb.reagents.urls.construct')),
	url(r'^vectors?/', include('experimentdb.reagents.urls.construct')),
	url(r'^plasmids?/', include('experimentdb.reagents.urls.construct')),
	url(r'^recombinant-?dna/', include('experimentdb.reagents.urls.construct')),

	url(r'^antibodys?/', include('experimentdb.reagents.urls.antibody')),
	url(r'^antibodies?/', include('experimentdb.reagents.urls.antibody')),

	url(r'^primers?/', include('experimentdb.reagents.urls.primer')),

	url(r'^cells?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cell-?lines?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cultured-cell-?lines?/', include('experimentdb.reagents.urls.cell')),

	url(r'^chemicals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^drugs?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^pharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^biopharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	
	url(r'^strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeast_?strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeasts?/', include('experimentdb.reagents.urls.strain')),
    
    url(r'^licenses?/', include('experimentdb.reagents.urls.license')),
    url(r'^mtas?/', include('experimentdb.reagents.urls.license')),
	
	(r'^clones?/', include('experimentdb.cloning.urls')),
	(r'^clonings?/', include('experimentdb.cloning.urls')),
	
	(r'^shipments?/', include('experimentdb.sharing.urls')),
	(r'^sharings?/', include('experimentdb.sharing.urls')),
	(r'^sent_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped?/', include('experimentdb.sharing.urls')),

        (r'^vendors?/', include('experimentdb.external.urls.vendor')),
        (r'^company/', include('experimentdb.external.urls.vendor')),
        (r'^companies/', include('experimentdb.external.urls.vendor')),
        (r'^contacts?/', include('experimentdb.external.urls.contact')),
        (r'^references?/', include('experimentdb.external.urls.reference')),
	

	(r'^pi35p2bp/$', 'django.views.generic.list_detail.object_list', {
		"queryset": PI35P2_Binding_Screen_SP.objects.all(),
		'template_name': 'gene_list.html',
		}),
	)

data/models.py
from django.db import models

from experimentdb.projects.models import Project, SubProject
from experimentdb.proteins.models import Protein
from experimentdb.reagents.models import Construct, Antibody, Cell, Primer, Chemical, Strain, AnimalStrain
from experimentdb.external.models import Contact, Reference

class Protocol(models.Model):
    """Describes the protocol or protocols used to perform each experiment.  
    
    This model stores information about the protocol used for an experiment.    

    An experiment may have several protocols attached to it.  For example, one could culture and transfect cells, then generate lysates then do some western blots.
    
    Since migrating to a mediawiki based protocol storage system, the wiki_page attribute indicates the protocol wiki page.  In this model, the **protocol_revision** attribute indicates the particular revision of the protocol used for that particular experiment.  In this way a permalink can be generated to the specific protocol used for a particular experiment.  To find the protocol revision number, mouse over the permanent link on the protocol and record the number at the end of the url.
    """
       
    protocol = models.CharField(max_length=50)
    protocol_slug = models.SlugField(max_length=25)
    #reference = models.ManyToManyField(Reference, blank=True)
    protocol_file = models.FileField(upload_to='protocol', blank=True)
    protocol_revision = models.IntegerField(blank=True, null=True, help_text="ProtocolWiki page revision number")
    wiki_page = models.CharField(max_length=75, blank=True, help_text="ProtocolWiki page (via MediaWiki)")
    comments = models.TextField(max_length=500, blank=True)	
    public = models.BooleanField()
    published = models.BooleanField()
    inactive = models.BooleanField()
    def __unicode__(self):
        return u'%s ' % self.protocol
    def get_absolute_url(self):
        return "/experimentdb/protocol/%i/" % self.id
	class Meta:
		ordering = ['-protocol']


class Experiment(models.Model):
    """Experiment objects are the central objects of this database.
    
    Experiment objects contain all details about an experiment including reagents, parameters, notes, results and data."""
    project = models.ManyToManyField(Project, blank=True, null=True)
    subproject = models.ManyToManyField(SubProject, blank=True, null=True)
    experimentID = models.SlugField(max_length=50, help_text="ie DB-2008-11-11-A", primary_key=True)
    experiment = models.CharField(max_length=100)
    protocol = models.ManyToManyField(Protocol, blank=True, null=True)
    assay = models.CharField(max_length=100, blank=True, null=True)
    experiment_date = models.DateField(help_text="Date Performed")
    cellline = models.ManyToManyField(Cell, blank=True, null=True)
    antibodies = models.ManyToManyField(Antibody, blank=True, null=True)
    chemicals = models.ManyToManyField(Chemical, blank=True, null=True)
    constructs = models.ManyToManyField(Construct, blank=True, null=True)
    siRNA = models.ManyToManyField(Primer, blank=True, null=True, limit_choices_to = {'primer_type': 'siRNA'})
    strain = models.ManyToManyField(Strain, blank=True, null=True)
    animal_model = models.ManyToManyField(AnimalStrain, blank=True, null=True)
    animal_cohort = models.ManyToManyField('AnimalCohort', blank=True, null=True)
    comments = models.TextField(max_length=500, blank=True, null=True)
    researcher = models.ManyToManyField(Contact, blank=True, null=True)
    protein = models.ManyToManyField(Protein, blank=True, null=True)
    public = models.BooleanField()
    published = models.BooleanField()
    sample_storage = models.CharField(max_length=100, blank=True)
    def __unicode__(self):
        """The unicode representation of an experiment object is the experiment on assay; date."""
        return u'%s on %s; %s' % (self.experiment, self.assay, self.experiment_date)
    def get_absolute_url(self):
        """The default url for an experiment is /experimentdb/experiment/experimentID."""
        return "/experimentdb/experiment/%s/" % self.experimentID
    class Meta:
        """The default ordering for experiments is in reverse of the experiment_date."""
        ordering = ['-experiment_date']

class Result(models.Model):
	experiment = models.ForeignKey(Experiment)
	conclusions = models.TextField(max_length=500, blank=True)
	#datafile = models.MultiFileField(upload_to='raw/%Y/%m/%d', blank=True)	
	file1 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	file2 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	file3 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan1 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan2 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan3 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan4 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan5 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	result_figure1 = models.ImageField(upload_to='final/%Y/%m/%d', blank=True)
	result_figure2 = models.ImageField(upload_to='final/%Y/%m/%d', blank=True)
	public = models.BooleanField()
	published = models.BooleanField()
	def __unicode__(self):
		return u'%s ' % self.experiment
	def get_absolute_url(self):
		return "/result/%i/" % self.id


class Sequencing(models.Model):
	clone_name = models.CharField(max_length=15)
	construct = models.ForeignKey(Construct)
	primer = models.ForeignKey(Primer)
	file = models.FileField(upload_to='sequencing/%Y/%m/%d', blank=True)
	sequence = models.CharField(max_length=1500)
	correct = models.BooleanField()
	notes = models.TextField(max_length=250,blank=True)
	date = models.DateField(blank=True)
	sample_number = models.IntegerField(max_length=8, blank=True, null=True)
	gel_number = models.IntegerField(max_length=8, blank=True, null=True)
	lane_number = models.IntegerField(max_length=3, blank=True, null=True)
	def __unicode__(self):
		return u'%s-%s' % (self.construct,self.clone_name)
        
class AnimalCohort(models.Model):

    """This model describes a particular cohort of animals.  
    
    As an example, an experiment might be dont with a particular knockout model, over several cohorts.
    This model defines two required classes, name and a many to many field for  :class:`~experimentdb.reagents.models.AnimalStrain`, and optional notes, start and end dates.
    The unicode name of this is "name" field and the url is /cohort/id where id is the primary key."""
    name = models.CharField(max_length=50)
    animal_model = models.ManyToManyField(AnimalStrain)
    date_start = models.DateField(blank=True, null=True, help_text="Cohort Start Date")
    date_end = models.DateField(blank=True, null=True, help_text="Cohort End Date")
    notes = models.TextField(blank=True, null=True)
    def __unicode__(self):
        return u'%s' % (self.name) 
    def get_absolute_url(self):
        return "/cohort/%i/" % self.id        

proteins/models.py
from django.db import models

class ProteinFamily(models.Model):
	name = models.CharField(max_length=50)
	notes = models.TextField(max_length=500, blank=True)
	def __unicode__(self):
		return '%s' % self.name
	@models.permalink
	def get_absolute_url(self):
		return ('protein-family-detail', [int(self.id)])		
	class Meta:
		ordering = ['name']
		verbose_name = "Protein Family"
		verbose_name_plural = "Protein Families"

class Protein(models.Model):
	protein_family = models.ManyToManyField('ProteinFamily')
	name = models.CharField(max_length=25)
	def __unicode__(self):
		return u'%s' % self.name
	@models.permalink
	def get_absolute_url(self):
		return ('protein-detail', [int(self.id)])
	class Meta:
		ordering = ['name']
		verbose_name_plural = "Proteins"
		
class Species(models.Model):
	common_name = models.CharField(max_length=50)
	scientific_name = models.CharField(max_length=50, blank=True)
	taxonomy_id = models.IntegerField(blank=True)
	def __unicode__(self):
		return '%s' % self.common_name
	class Meta:
		verbose_name_plural = "Species"
	
		
class ProteinDetail(models.Model):
	name = models.CharField(max_length=50, help_text="Our Name for the Protein")
	protein = models.ForeignKey('Protein')
	gene = models.CharField(max_length=10, blank=True)
	species = models.ForeignKey('Species')
	geneID = models.IntegerField(blank=True)
	RefSeqProtein = models.CharField(max_length=15, blank=True, verbose_name="Protein Sequence (RefSeq)")
	RefSeqProtein_gi = models.IntegerField(max_length=20, blank=True)
	RefSeqNucleotide = models.CharField(max_length=15, blank=True, verbose_name="Nucleotide Sequence (RefSeq)")
	RefSeqNucleotide_gi = models.IntegerField(max_length=10, blank=True)
	WormBaseID = models.CharField(max_length=50, blank=True)
	FlyBaseID = models.CharField(max_length=50, blank=True)
	SGD_ID = models.CharField(max_length=25, blank=True)
	public = models.BooleanField()
	published = models.BooleanField()
	def __unicode__(self):
		return u'%s' % self.name
	class Meta:
		verbose_name_plural = "Protein Isoforms"
	

proteins/forms.py
from django import forms
from experimentdb.proteins.models import Protein, ProteinFamily
from experimentdb.widgets import SelectWithPop


class ProteinForm(forms.ModelForm):
	protein_family = forms.ModelChoiceField(ProteinFamily.objects, widget=SelectWithPop)
	class Meta:
		model = Protein
		
class ProteinFamilyForm(forms.ModelForm):
	class Meta:
		model = ProteinFamily

proteins/templates/detail.html
{% extends "base.html" %}

{% block title %} Protein Detail {% endblock %}
{% block content %}
<h2>{{ protein }}</h2>

{% if antibodies %}
<table>
 <thead>
  <tr>
   <th>Antibodies ({{ antibodies.count }})</td>
  </tr>
 </thead>
 <tbody>
{% for antibody in antibodies %}
   <tr>
   <td><a href="/experimentdb/antibody/{{antibody}}">{{ antibody }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
{% endif %}

{% if constructs %}
<table>
 <thead>
  <tr>
   <th>Constructs ({{ constructs.count }})</td>
  </tr>
 </thead>
 <tbody>
{% for construct in constructs %}
   <tr>
   <td><a href="/experimentdb/construct/{{construct}}">{{ construct }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
{% endif %}

{% if purified_proteins %}
<table>
 <thead>
  <tr>
   <th>Purified Proteins ({{ purified_proteins.count }})</td>
  </tr>
 </thead>
 <tbody>
{% for protein in purified_proteins %}
   <tr>
   <td><a href="/experimentdb/purified_proteins/{{protein}}">{{ protein }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
{% endif %}

{% if primers %}
<table>
 <thead>
  <tr>
   <th>Primers ({{ primers.count }})</td>
  </tr>
 </thead>
 <tbody>
{% for primer in primers %}
   <tr>
   <td><a href="/experimentdb/primer/{{primer}}">{{ primer }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
{% endif %}




{% if experiment_protein %}
<table>
 <thead>
  <tr>
   <th>Experiments ({{ experiment_protein.count }})</td>
  </tr>
 </thead>
 <tbody>
{% for experiment in experiment_protein %}
   <tr>
   <td><a href="/experimentdb/experiment/{{experiment.experimentID}}">{{ experiment }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
{% endif %}
{% endblock %}

proteins/templates/index.html
{% extends "base.html" %}

{% block head_title %}Protein List{% endblock %}
{% block title %}Protein List{% endblock %}
{% block content %}
<table>
 <thead>
 </thead>
 <tdata>
  {% for name in protein_list %}
  <tr><td><a href="/experimentdb/protein/{{ name }}"> {{ name }}.</td></tr>
{% endfor %}
 </tdata>
{% endblock %}

proteins/templates/protein_detail.html
{% extends "base.html" %}
{% block head_title %}{{ protein }} - Detail {% endblock %}
{% block title %} {{ protein }} Detail {% endblock %}
{% block scripts %}
<script type="text/javascript">
	$(function() {
		$("#accordion").accordion({
			autoHeight: false
		});
	});
	</script>
{% endblock %}
{% block content %}
<h2>{{ protein }}</h2>
<h3>Protein Families</h3>
<ul>{% for family in protein.protein_family.all %}
 <li><a href="{{family.get_absolute_url}}">{{family}}</a></li>
{% endfor %}
 </ul>
<table>
 <thead>
  <tr>
   <th>Protein</th>
   <th>Species</th>
   <th>Gene</th>
   <th>Protein Sequence</th>
   <th>Nucleotide Sequence</th>
  </tr>
 </thead>
 <tbody>
  {% for protein_detail in protein.proteindetail_set.all %}
 <tr>
  <td>{{ protein_detail }}</td>
  <td>{{ protein_detail.species }}</td>
  <td><a href="http://www.ncbi.nlm.nih.gov/sites/entrez?Db=gene&Cmd=ShowDetailView&TermToSearch={{ protein_detail.geneID}}&ordinalpos=3&itool=EntrezSystem2.PEntrez.Gene.Gene_ResultsPanel.Gene_RVDocSum" title = "NCBI Gene Record for {{protein_detail.gene}}", target="_blank">{{ protein_detail.gene }}</a></td>
  <td><a href="http://www.ncbi.nlm.nih.gov/protein/{{ protein_detail.RefSeqProtein_gi}}", title ="NCBI Protein Record for {{protein_detail.RefSeqProtein}}" target="_blank">{{ protein_detail.RefSeqProtein }}</a></td>
  <td><a href="http://www.ncbi.nlm.nih.gov/nuccore/{{ protein_detail.RefSeqNucleotide_gi}}", title ="NCBI Nucleotide Record for {{protein_detail.RefSeqNucleotide}}" target="_blank">{{ protein_detail.RefSeqNucleotide }}</a></td>
  {% ifequal protein_detail.species.scientific_name "Drosophila melanogaster" %}<td><a href="http://flybase.org/reports/{{ protein_detail.FlyBaseID }}.html" title="FlyBase Record for {{ protein_detail.FlyBaseID }}", target="_blank"><img src="http://www.fly-ted.org/images/fly_logo.png", height="25px"></a></td>{% endifequal %}
  {% ifequal protein_detail.species.scientific_name "Caenorhabditis elegans" %}<td><a href="http://www.wormbase.org/db/gene/gene?class=CDS;name={{ protein_detail.WormBaseID }}.html" title="WormBase Record for {{ protein_detail.WormBaseID }}", target="_blank"><img src="http://www.its.caltech.edu/~wormbase/logo.jpg", height="25px"</a></td>{% endifequal %}
  {% ifequal protein_detail.species.scientific_name "Saccharomyces cerevisiae" %}<td><a href="/experimentdb/sgd/{{protein_detail.gene}}">{{protein_detail.gene}}</a></td><td><a href="http://www.yeastgenome.org/cgi-bin/locus.fpl?locus={{ protein_detail.SGD_ID }}", title="SGD Record for {{ protein_detail.SGD_ID }}", target="_blank"><img src="http://www.pebc.cat/Bioinformatic/SGD_logo.png", height="25px"</a></td>{% endifequal %}
  </tr>
{% endfor %}
 </tbody>
 </table>
 <p>Add new protein isoform <a href="/experimentdb/protein_isoform/new">here</a></p>

<div id ="accordion">
<h3><a href="#">Antibodies ({{ protein.antibody_set.count }})</a></h3>
<div>
<table>
 <thead>
 </thead>
 <tbody>
{% for antibody in protein.antibody_set.all %}
   <tr>
   <td><a href="/experimentdb/antibody/{{antibody.id}}">{{ antibody }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
  </div>




<h3><a href="#">Constructs ({{ protein.construct_set.count }})</a></h3>
<div>
<table>
 <thead>
 </thead>
 <tbody>
{% for construct in protein.construct_set.all %}
   <tr>
   <td><a href="{{ construct.get_absolute_url }}">{{ construct }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
  </div>

<h3><a href="#">Primers ({{protein.primer_set.count}})</a></h3>
<div>
<table>
 <thead>
  <th>Primer</th>
  <th>Type</th>
  <th>Sequence</th>
 </thead>
 <tbody>
{% for primer in protein.primer_set.all %}
   <tr>
   <td><a href="{{primer.get_absolute_url}}">{{ primer }}</a></td>
   <td>{{ primer.primer_type }}
   <td>{{ primer.sequence }}
   </tr>
  </tbody>
{% endfor %}
  </table>
  </div>


<h3><a href="#">Strains ({{protein.strain_set.count}})</a></h3>
<div>
<table>
 <thead>
 </thead>
 <tbody>
{% for strain in protein.strain_set.all %}
   <tr>
   <td><a href="{{strain.get_absolute_url}}" title="strain">{{ strain|safe }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
  </div>

<h3><a href="#">Experiments ({{ protein.experiment_set.count }})</a></h3>
<div>
<table>
 <thead>
 </thead>
 <tbody>
{% for experiment in protein.experiment_set.all %}
   <tr>
   <td><a href="{{experiment.get_absolute_url }}">{{ experiment }}</a></td>
   </tr>
  </tbody>
{% endfor %}
  </table>
  </div>

{% with protein as object %}
{% include "comment.html" %}
{% endwith %}
  </div>
{% endblock %}

proteins/templates/protein_family_detail.html
{% extends "base.html" %}

{% block head_title %}Protein List - {{object}}{% endblock %}
{% block title %}Protein List - {{object}}{% endblock %}
{% block content %}
<h1>{{ object }}</h1>
<table>
 <thead>
    <tr><th>Protein</th><th>Experiments</th><th>Constructs</th><th>Antibodies</th><th>Primers</th><th>Strains</th></tr>
 </thead>
 <tdata>
  {% for protein in object.protein_set.all %}
  <tr>
   <td><a href="/{{ protein.get_absolute_url }}" title="{{ protein }}"> {{ protein }}</a></td>
   <td>{{ protein.experiment_set.count }}</td>
   <td>{{ protein.construct_set.count }}</td>
   <td>{{ protein.antibody_set.count }}</td>
   <td>{{ protein.primer_set.count }}</td>
   <td>{{ protein.strain_set.count }}</td>
  </tr>
  {% endfor %}
 </tdata>
</table>
{% include "comment.html" %}
{% endblock %}

proteins/templates/protein_family_form.html
{% extends "base.html" %}
{% block head_title %}New Protein Family{% endblock %}
{% block title %}New Protein Family{% endblock %}
{% block content %}
<form method="POST" action="/experimentdb/protein/family/new/">{% csrf_token %}
<table class="sortable">
{{form}}
 </table>
 <input type="submit" value="Submit" />
 </form>
 
{% endblock %}

proteins/templates/protein_family_list.html.html
{% extends "base.html" %}

{% block head_title %}Protein Family List{% endblock %}
{% block title %}Protein Family List{% endblock %}
{% block content %}
<table>
 <thead>
 </thead>
 <tdata>
  {% for family in object_list %}
  <tr><td><a href="/experimentdb/protein/family/{{ family }}"> {{ family }}.</td><td>{{ family.notes }}</tr>
{% endfor %}
 </tdata>
{% endblock %}