urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
admin.autodiscover()
from experimentdb.datasets.models import SGD_GeneNames, SGD_phenotypes, PI35P2_Binding_Screen_SP

urlpatterns = patterns('',
	(r'^admin/', include(admin.site.urls)),
	(r'^accounts/login/', 'django.contrib.auth.views.login'),
	(r'^comments?/', include('django.contrib.comments.urls')),
	(r'^search/$', 'experimentdb.views.search'),
	(r'^ajax_select/', include('ajax_select.urls')),
	(r'^add/protein_family/?$', 'experimentdb.proteins.views.newProteinFamily'),

	(r'^experiments?/', include('experimentdb.data.urls.experiment')),
	(r'^exps?/', include('experimentdb.data.urls.experiment')),

	url(r'^projects?/', include('experimentdb.projects.urls.project')),
	url(r'^subprojects?/', include('experimentdb.projects.urls.subproject')),

	url(r'^hypotheses/', include('experimentdb.hypotheses.urls.hypotheses')),
	url(r'^process/', include('experimentdb.hypotheses.urls.process')),
	url(r'^manipulation/', include('experimentdb.hypotheses.urls.manipulation')),    

	(r'^proteins?/', include('experimentdb.proteins.urls')),

	url(r'^reagents?/$', 'experimentdb.reagents.views.index', name="reagent-list"),

	url(r'^protocols?/', include('experimentdb.data.urls.protocol')),
	url(r'^protocols?/$', 'experimentdb.data.views.protocol_list'),
	url(r'^protocols?/(?P<protocol_slug>[-\w\d]+)/$', 'experimentdb.data.views.protocol_detail'),
	url(r'^sgd/(?P<gene>[-\w\d]+)/$', 'experimentdb.datasets.views.sgd_gene_detail', name="sgd-gene-detail"),

	url(r'^constructs?/', include('experimentdb.reagents.urls.construct')),
	url(r'^vectors?/', include('experimentdb.reagents.urls.construct')),
	url(r'^plasmids?/', include('experimentdb.reagents.urls.construct')),
	url(r'^recombinant-?dna/', include('experimentdb.reagents.urls.construct')),

	url(r'^antibodys?/', include('experimentdb.reagents.urls.antibody')),
	url(r'^antibodies?/', include('experimentdb.reagents.urls.antibody')),

	url(r'^primers?/', include('experimentdb.reagents.urls.primer')),

	url(r'^cells?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cell-?lines?/', include('experimentdb.reagents.urls.cell')),
	url(r'^cultured-cell-?lines?/', include('experimentdb.reagents.urls.cell')),

	url(r'^chemicals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^drugs?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^pharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	url(r'^biopharmaceuticals?/', include('experimentdb.reagents.urls.chemical')),
	
	url(r'^strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeast_?strains?/', include('experimentdb.reagents.urls.strain')),
	url(r'^yeasts?/', include('experimentdb.reagents.urls.strain')),
    
    url(r'^licenses?/', include('experimentdb.reagents.urls.license')),
    url(r'^mtas?/', include('experimentdb.reagents.urls.license')),
	
	(r'^clones?/', include('experimentdb.cloning.urls')),
	(r'^clonings?/', include('experimentdb.cloning.urls')),
	
	(r'^shipments?/', include('experimentdb.sharing.urls')),
	(r'^sharings?/', include('experimentdb.sharing.urls')),
	(r'^sent_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped_items?/', include('experimentdb.sharing.urls')),
	(r'^shipped?/', include('experimentdb.sharing.urls')),

        (r'^vendors?/', include('experimentdb.external.urls.vendor')),
        (r'^company/', include('experimentdb.external.urls.vendor')),
        (r'^companies/', include('experimentdb.external.urls.vendor')),
        (r'^contacts?/', include('experimentdb.external.urls.contact')),
        (r'^references?/', include('experimentdb.external.urls.reference')),
	

	(r'^pi35p2bp/$', 'django.views.generic.list_detail.object_list', {
		"queryset": PI35P2_Binding_Screen_SP.objects.all(),
		'template_name': 'gene_list.html',
		}),
	)

data/models.py
from django.db import models

from experimentdb.projects.models import Project, SubProject
from experimentdb.proteins.models import Protein
from experimentdb.reagents.models import Construct, Antibody, Cell, Primer, Chemical, Strain, AnimalStrain
from experimentdb.external.models import Contact, Reference

class Protocol(models.Model):
    """Describes the protocol or protocols used to perform each experiment.  
    
    This model stores information about the protocol used for an experiment.    

    An experiment may have several protocols attached to it.  For example, one could culture and transfect cells, then generate lysates then do some western blots.
    
    Since migrating to a mediawiki based protocol storage system, the wiki_page attribute indicates the protocol wiki page.  In this model, the **protocol_revision** attribute indicates the particular revision of the protocol used for that particular experiment.  In this way a permalink can be generated to the specific protocol used for a particular experiment.  To find the protocol revision number, mouse over the permanent link on the protocol and record the number at the end of the url.
    """
       
    protocol = models.CharField(max_length=50)
    protocol_slug = models.SlugField(max_length=25)
    #reference = models.ManyToManyField(Reference, blank=True)
    protocol_file = models.FileField(upload_to='protocol', blank=True)
    protocol_revision = models.IntegerField(blank=True, null=True, help_text="ProtocolWiki page revision number")
    wiki_page = models.CharField(max_length=75, blank=True, help_text="ProtocolWiki page (via MediaWiki)")
    comments = models.TextField(max_length=500, blank=True)	
    public = models.BooleanField()
    published = models.BooleanField()
    inactive = models.BooleanField()
    def __unicode__(self):
        return u'%s ' % self.protocol
    def get_absolute_url(self):
        return "/experimentdb/protocol/%i/" % self.id
	class Meta:
		ordering = ['-protocol']


class Experiment(models.Model):
    """Experiment objects are the central objects of this database.
    
    Experiment objects contain all details about an experiment including reagents, parameters, notes, results and data."""
    project = models.ManyToManyField(Project, blank=True, null=True)
    subproject = models.ManyToManyField(SubProject, blank=True, null=True)
    experimentID = models.SlugField(max_length=50, help_text="ie DB-2008-11-11-A", primary_key=True)
    experiment = models.CharField(max_length=100)
    protocol = models.ManyToManyField(Protocol, blank=True, null=True)
    assay = models.CharField(max_length=100, blank=True, null=True)
    experiment_date = models.DateField(help_text="Date Performed")
    cellline = models.ManyToManyField(Cell, blank=True, null=True)
    antibodies = models.ManyToManyField(Antibody, blank=True, null=True)
    chemicals = models.ManyToManyField(Chemical, blank=True, null=True)
    constructs = models.ManyToManyField(Construct, blank=True, null=True)
    siRNA = models.ManyToManyField(Primer, blank=True, null=True, limit_choices_to = {'primer_type': 'siRNA'})
    strain = models.ManyToManyField(Strain, blank=True, null=True)
    animal_model = models.ManyToManyField(AnimalStrain, blank=True, null=True)
    animal_cohort = models.ManyToManyField('AnimalCohort', blank=True, null=True)
    comments = models.TextField(max_length=500, blank=True, null=True)
    researcher = models.ManyToManyField(Contact, blank=True, null=True)
    protein = models.ManyToManyField(Protein, blank=True, null=True)
    public = models.BooleanField()
    published = models.BooleanField()
    sample_storage = models.CharField(max_length=100, blank=True)
    def __unicode__(self):
        """The unicode representation of an experiment object is the experiment on assay; date."""
        return u'%s on %s; %s' % (self.experiment, self.assay, self.experiment_date)
    def get_absolute_url(self):
        """The default url for an experiment is /experimentdb/experiment/experimentID."""
        return "/experimentdb/experiment/%s/" % self.experimentID
    class Meta:
        """The default ordering for experiments is in reverse of the experiment_date."""
        ordering = ['-experiment_date']

class Result(models.Model):
	experiment = models.ForeignKey(Experiment)
	conclusions = models.TextField(max_length=500, blank=True)
	#datafile = models.MultiFileField(upload_to='raw/%Y/%m/%d', blank=True)	
	file1 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	file2 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	file3 = models.FileField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan1 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan2 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan3 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan4 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	rawscan5 = models.ImageField(upload_to='raw/%Y/%m/%d', blank=True)
	result_figure1 = models.ImageField(upload_to='final/%Y/%m/%d', blank=True)
	result_figure2 = models.ImageField(upload_to='final/%Y/%m/%d', blank=True)
	public = models.BooleanField()
	published = models.BooleanField()
	def __unicode__(self):
		return u'%s ' % self.experiment
	def get_absolute_url(self):
		return "/result/%i/" % self.id


class Sequencing(models.Model):
	clone_name = models.CharField(max_length=15)
	construct = models.ForeignKey(Construct)
	primer = models.ForeignKey(Primer)
	file = models.FileField(upload_to='sequencing/%Y/%m/%d', blank=True)
	sequence = models.CharField(max_length=1500)
	correct = models.BooleanField()
	notes = models.TextField(max_length=250,blank=True)
	date = models.DateField(blank=True)
	sample_number = models.IntegerField(max_length=8, blank=True, null=True)
	gel_number = models.IntegerField(max_length=8, blank=True, null=True)
	lane_number = models.IntegerField(max_length=3, blank=True, null=True)
	def __unicode__(self):
		return u'%s-%s' % (self.construct,self.clone_name)
        
class AnimalCohort(models.Model):

    """This model describes a particular cohort of animals.  
    
    As an example, an experiment might be dont with a particular knockout model, over several cohorts.
    This model defines two required classes, name and a many to many field for  :class:`~experimentdb.reagents.models.AnimalStrain`, and optional notes, start and end dates.
    The unicode name of this is "name" field and the url is /cohort/id where id is the primary key."""
    name = models.CharField(max_length=50)
    animal_model = models.ManyToManyField(AnimalStrain)
    date_start = models.DateField(blank=True, null=True, help_text="Cohort Start Date")
    date_end = models.DateField(blank=True, null=True, help_text="Cohort End Date")
    notes = models.TextField(blank=True, null=True)
    def __unicode__(self):
        return u'%s' % (self.name) 
    def get_absolute_url(self):
        return "/cohort/%i/" % self.id        

data/forms.py
"""This module contains forms for use in the data package.

The current contents are ExperimentForm and ResultForm, both of which are ModelForms for adding or editing Experiments and Results.
"""

from django import forms
from django.contrib.admin import widgets
from django.forms.models import inlineformset_factory

from ajax_select.fields import AutoCompleteSelectMultipleField, AutoCompleteSelectField

from experimentdb.data.models import Experiment, Result

class ExperimentForm(forms.ModelForm):
    """This is a modelform for the creation and editing of experimental data."""
    antibodies = AutoCompleteSelectMultipleField('antibody', required=False)
    constructs = AutoCompleteSelectMultipleField('construct', required=False)	
    cellline = AutoCompleteSelectMultipleField('cell', required=False)
    chemicals = AutoCompleteSelectMultipleField('chemical', required=False)
    siRNA = AutoCompleteSelectMultipleField('siRNA', required=False)	
    strain = AutoCompleteSelectMultipleField('strain', required=False)	
    protein = AutoCompleteSelectMultipleField('protein', required=False)		
    protocol = AutoCompleteSelectMultipleField('protocol', required=False)	
    class Meta:
        model = Experiment
    class Media:
        """This form requires both a css and javascript file for the autocomplete function.
        
        The css/autocomplete.css file has been customized to match the vader theme."""
        css = {
		    'all': ('css/autocomplete.css',),
              }
        js = ("js/jquery-autocomplete/jquery.autocomplete.js",)


	
		
class ResultForm(forms.ModelForm):
	"""This is a modelform for the creation and editing of specific results."""
	class Meta:
		model = Result
		exclude = ['experiment']
		
ResultFormSet = inlineformset_factory(Experiment, Result, can_delete=True, extra=5)

data/views.py
"""This module provides the views for working with the data package.
This module will generate index and detail views for experiments and protocols as well as for the form to enter new results through an experiment.  Several other generic views are found in data.urls.
"""

from django.db.models import Q
from django.shortcuts import render_to_response, get_object_or_404
from experimentdb.data.models import Experiment, Result, Protocol
from experimentdb.data.forms import ResultForm, ResultFormSet, ExperimentForm
from experimentdb.proteins.models import Protein
from experimentdb.reagents.models import Chemical, Antibody, Cell
from experimentdb.projects.models import Project, SubProject
from experimentdb.external.models import Reference, Contact
from django.contrib.auth.decorators import login_required, permission_required
from django.template import RequestContext
from django.http import HttpResponseRedirect


@login_required
def index(request):
	"""This view shows a list of all experiments.

	This list is ordered by the experiment date in descending order.  This view could potentially be rendered by a generic view.
	"""
	experiment_list = Experiment.objects.order_by('-experiment_date')
	return render_to_response('experiment_list.html', {'experiment_list': experiment_list},context_instance=RequestContext(request))

@login_required
def experiment(request, experimentID):
	"""This renders a detailed page of an experiment.

	The view will show the experiment, and all associated reagents, proteins, projects and results associated with this object.
	"""
	experiment = get_object_or_404(Experiment, pk=experimentID)
	return render_to_response('experiment.html', {'experiment':experiment}, context_instance=RequestContext(request))

@login_required
def protocol_list(request):
	"""This renders a view in which all protocols are displayed.

	In the case of deprecated protocols (i.e. protocols not marked as active), these are not shown.  This view could also be rendered as a generic view.
	"""
	protocol_list = Protocol.objects.all()
	return render_to_response('protocol_list.html', {'protocol_list':protocol_list, },context_instance=RequestContext(request))

@login_required
def protocol_detail(request, protocol_slug):
	"""This renders a view in which a protocol detail page is shown.

	This view should be deprecated in favor of a redirection directly to the wiki page for this protocol
	"""
	protocol = get_object_or_404(Protocol, protocol_slug=protocol_slug)
	protocol_experiments = Experiment.objects.filter(protocol=protocol)	
	return render_to_response ('protocol_detail.html', {'protocol': protocol, 'protocol_experiments':protocol_experiments},context_instance=RequestContext(request))

@login_required
def result_new(request, experimentID):
	"""This renders a form to add a new result.

	This view will be sent from a particular experiment and will attach the result to that particular experiment.	
	"""
	experiment = get_object_or_404(Experiment, pk=experimentID)
	if request.method == "POST":
		form = ResultForm(request.POST, request.FILES)
		if form.is_valid():
			result = form.save(commit=False)
			result.experiment_id = experiment.experimentID
			result.save()
			form.save()
			return HttpResponseRedirect( experiment.get_absolute_url() )
	else:
		form = ResultForm()
	return render_to_response('result_form.html', {'form':form, 'experiment':experiment},context_instance=RequestContext(request))
	
@permission_required('data.change_experiment')
def experiment_edit(request, experimentID):
    """Renders a form to edit an experiment and associated formsets for experimental results.
	
    Takes a request in the form of experiment/(experimentID)/edit and returns the experiment_result_form.html form."""
    experiment = get_object_or_404(Experiment, pk=experimentID)
    if request.method == "POST":
        form = ExperimentForm(request.POST)
        if form.is_valid():
            experiment = form.save(commit=False)
            formset = ResultFormSet(request.POST, instance=experiment)
            if result_formset.is_valid():
                experiment.save()
                result_formset.save()                
            return HttpResponseRedirect( experiment.get_absolute_url() )
    else:
        form = ExperimentForm()
        formset = ResultFormSet(instance=Experiment())
    return render_to_response("experiment_result_form.html", {"form": form,"formset": formset,}, context_instance=RequestContext(request))

data/templates/experiment.html
{% extends "base.html" %}
{% block head_title %}Experiment Summary - {{experiment}}{% endblock %}
{% block title %}Experiment Summary - {{experiment}}{% endblock %}
{% block scripts %}
<link rel="stylesheet" href="{{STATIC_URL}}js/colorbox/example5/colorbox.css" type="text/css" media="screen" />
<script type="text/javascript" src="{{STATIC_URL}}js/colorbox/colorbox/jquery.colorbox.js"></script>
<script type="text/javascript">
	$(function() {
		$("#accordion").accordion({
			autoHeight: false
            });
        $("a[rel='figures']").colorbox({height:"75%"});
	});
</script>

{% endblock %}

{% block content %}
<div class id="accordion">
	<h3><a href="#">General</a></h3>
	<div id="General">
	<table>
	<tr><th>Date</th><td>{{ experiment.experiment_date}}</td></tr>
	<tr><th>Assay</th><td>{{ experiment.assay}}</td></tr>
	<tr><th>Experiment</th><td>{{ experiment.experiment}}</td></tr>
	{% for protocol in experiment.protocol.all %}
	<tr><th>Protocol</th><td><a href="{{protocol.get_absolute_url}}">{{protocol}}</td></tr>
	{% endfor %}
	</table>
	<h3>Notes</h3>
	<p>{{experiment.comments}}</p>
	</div>

	<h3><a href="#">Projects</a></h3>
	<div id="Projects">
	<ul>
	{% for project in experiment.project.all %}
	<li><a href="{{ project.get_absolute_url }}">{{project}}</a></li>
	{% endfor %}
	</ul>
	
	
	<ul>
	<ul>
	{% for subproject in experiment.subproject.all %}
	<li><a href="{{ subproject.get_absolute_url }}">{{subproject}}</a></li>
	{% endfor %}
	</ul>
	</div>
	
	<h3><a href="#">Hypotheses</a></h3>	
	<div id="hypotheses">
	<ul>
	{% for evidence in experiment.evidence_set.all %}
	{% for hypothesis in evidence.hypothesis_set.all %}
	<li>{{evidence.citation_type}} -- <a href="{{hypothesis.get_absolute_url }}">{{ hypothesis }}</a></li>
	{% endfor %}
	{% endfor %}
	</ul>
	</div>
	
	<h3><a href="#">Researchers</a></h3>	
	<div id="Researchers">
	<ul>
	{% for researcher in experiment.researcher.all %}
	<li>{{researcher}}</li>
	{% endfor %}
	</ul>
	</div>
	
	<h3><a href="#">Proteins</a></h3>
	<div id="Proteins">
	 <ul>{% for protein in experiment.protein.all %}<li><a href="/{{protein.get_absolute_url}}">{{protein}}</a></li>{% endfor %}</ul>
	</div>

	<h3><a href="#">Results and Conclusions</a></h3>
	<div id="conclusions">
	<h4>Results</h4>	
	{% for result in experiment.result_set.all %}
	<p>{{ result.conclusions }}</p>
	{% if result.result_figure1 %}<a href="{{result.result_figure1.url}}" rel="figures" ><img class="figure" alt="Figure 1" src="{{result.result_figure1.url}}" width=200 /></a>{% endif %}
	{% if result.result_figure2 %}<a href="{{result.result_figure2.url}}" rel="figures" ><img class="figure" alt="Figure 2" src="{{result.result_figure2.url}}" width=200 /></a>{% endif %}
	{% endfor %}
	<p>Add new result <a href="/experimentdb/experiment/{{experiment.experimentID}}/result/new"><img src="{{STATIC_URL}}img/icons/add.png" width=25 alt="here"/></a></p></div>

	<h3><a href="#">Reagents</a></h3>
	<div id="reagents">
	<h4>Chemicals:</h4> 
		<ul>{% for chemical in experiment.chemicals.all %}
			<li><a href="{{chemical.get_absolute_url}}">{{chemical}}</a></li>{% endfor %}
		</ul>

	<h4>Cell Lines:</h4> 
		<ul>{% for cell in experiment.cellline.all %}
			<li><a href="{{cell.get_absolute_url}}">{{cell}}</a></li>{% endfor %}
		</ul>
		
	<h4>Constructs:</h4> 
		<ul>{% for construct in experiment.constructs.all %}
			<li><a href="{{construct.get_absolute_url}}">{{construct}}</a></li>{% endfor %}
		</ul>

	<h4>Antibodies:</h4>
		<ul>{% for antibody in experiment.antibodies.all %}
		<li><a href="{{antibody.get_absolute_url}}">{{antibody}}</a></li>{% endfor %}</ul>
		
	<h4>Primers:</h4>
		<ul>{% for primer in experiment.siRNA.all %}
		<li><a href="{{primer.get_absolute_url}}">{{primer}}</a></li>{% endfor %}</ul>
		
	<h4>Strains:</h4>
		<ul>{% for strain in experiment.strain.all %}
		<li><a href="{{strain.get_absolute_url}}">{{strain|safe}}</a></li>{% endfor %}</ul>
	</div>

	<h3><a href="#">Raw Data Files</a></h3>
	<div id="files">
	{% for result in experiment.result_set.all %}
	<ul>
	{% if result.file1 %}<li><a href="{{result.file1.url}}">{{result.file1}}</a></li>{% endif %}
	{% if result.file2 %}<li><a href="{{result.file2.url}}">{{result.file2}}</a></li>{% endif %}
	{% if result.file3 %}<li><a href="{{result.file3.url}}">{{result.file3}}</a></li>{% endif %}
	{% if result.rawscan1 %}<li><a href="{{result.rawscan1.url}}">{{result.rawscan1}}</a></li>{% endif %}
	{% if result.rawscan2 %}<li><a href="{{result.rawscan2.url}}">{{result.rawscan2}}</a></li>{% endif %}
	{% if result.rawscan3 %}<li><a href="{{result.rawscan3.url}}">{{result.rawscan3}}</a></li>{% endif %}
	{% if result.rawscan4 %}<li><a href="{{result.rawscan4.url}}">{{result.rawscan4}}</a></li>{% endif %}
	{% if result.rawscan5 %}<li><a href="{{result.rawscan5.url}}">{{result.rawscan5}}</a></li>{% endif %}
	{% endfor %}
	</ul>
	</div>

{% with experiment as object %}
{% include "comment.html" %}
{% endwith %}
</div>
{% endblock %}

data/templates/experiment_form.html
{% extends "base.html" %}
{% block head_title %}New Experiment{% endblock %}
{% block title %}New Experiment{% endblock %}
{% block scripts %}
{{ form.media }}
	<script type="text/javascript">
	 $(document).ready(function() {	
		$('#id_experiment_date').datepicker({dateFormat: 'yy-mm-dd'});
	});
	</script>
{% endblock %}
{% block content %}
<form method="POST" action="/experimentdb/experiment/new/">{% csrf_token %}
<table class="sortable">
{{form}}
 </table>
 <input type="submit" value="Submit" />
 </form>
 
{% endblock %}

data/templates/experiment_list.html
{% extends "base.html" %}
{% block head_title %}Experiment List{% endblock %}
{% block title %}Experiment List{% endblock %}
{% block content %}
<a class="fg-button ui-state-default ui-corner-all" href="/experimentdb/experiment/new" la>Add a new experiment</a>
<div = "experiments">
{% include "experiment_list_table.html" %}
</div>
{% endblock %}

data/templates/experiment_list_table.html
<h2>Experiments ({{experiment_list.count}})</h2>
<table>
	<thead>
		<tr>
		<th>ID</th>
		<th>Assay</th>
		<th>Experiment</th>
		</tr>
	<thead>
	<tbody>
	{% for experiment in experiment_list %}
		<tr>
		<td><a href="/experimentdb/experiment/{{experiment.experimentID}}">{{ experiment.experimentID }}</td>
		<td>{{ experiment.assay }}</td>
		<td>{{ experiment.experiment }}</td>
		</tr>
	</tbody>
{% endfor %}
</table>

data/templates/experiment_result_form.html
{% extends "base.html" %}
{% block head_title %}New Experiment{% endblock %}
{% block title %}New Experiment{% endblock %}
{% block scripts %}
	<script type="text/javascript">
	 $(document).ready(function() {	
		$('#id_experiment_date').datepicker({dateFormat: 'yy-mm-dd'});
	});
	</script>
{% endblock %}
{% block content %}
<form method="POST" action=".">
<table>
{{form.as_table}}
<p>{{ formset }}</p>
   <tr>
        <th></th>
        <td><input type="submit" name="submit" value="Submit" class="button"></td>
      </tr>
    </table>
  </form>

 </form>
 
 
{% endblock %}

data/templates/protocol_detail.html
{% extends "base.html" %}
{% block head_title %}Protocol: {{ object }}{% endblock %}
{% block title %}{{ object }}{% endblock %}


{% block content %}
<h2>View Protocol</h2>
{% if object.wiki_page %}<ul><li>Wiki - <a href="/wiki/{{object.wiki_page}}">{{ object }}</a></li></ul>{% endif %}
{% if object.protocol_file %}<ul><li>File - <a href="{{object.protocol_file.url}}">{{ object }}</a></li></ul>{% endif %}
<h2>Experiments</h2>
<ul>
{% for experiment in object.experiment_set.all %}
<li><a href="{{ experiment.get_absolute_url }}">{{ experiment }}</a></li>
{% endfor %}
</ul>
{% endblock content %}

data/templates/protocol_form.html
{% extends "base.html" %}

{% block head_title %}{% if object %}Update Protocol {{object}}{% else %} New Protocol {% endif %}{% endblock %}
{% block title %}{% if object %}Update Protocol {{object}}{% else %} New Protocol {% endif %}{% endblock %}
{% block content %}
<form enctype="multipart/form-data"  method="post" {% if object %} action="{% url protocol-edit object.id %}"{% else %} action="{% url protocol-new %}"{% endif%}>{% csrf_token %}
<table>{{ form }}</table>
<input type="submit" value="Submit"/>
</form>
{% endblock %}

data/templates/protocol_list.html
{% extends "base.html" %}
{% block scripts %}
	<script type="text/javascript" src="/javascript/jquery-1.3.2.js"></script> 
	<script type="text/javascript" src="/javascript/dataTables-1.4/media/js/jquery.dataTables.js"</script>
	<script type="text/javascript">
	$(document).ready(function() { 
		$(".sortable").dataTable( {
			"bPaginate": false,
			});
		});
    	</script>
{% endblock scripts %}
{% block head_title %}Protocols{% endblock %}
{% block title %}Protocols{% endblock %}
{% block content %}
{% if perms.data.add_protocol %}<p>Click <a href="{% url protocol-new %}"><img src="{{STATIC_URL}}img/icons/Add.png" width=25 alt="here"></a> for a new protocol</p>{% endif %}
<h2>Protocols ({{object_list.count}})</h2>
<table class="sortable">
<thead>
<tr>
	<th>Protocol</th>
	<th>Wiki Page</th>
</tr>
</thead>
<tbody>
{% for protocol in object_list %}
<tr>
	<td><a href="{% url protocol-detail protocol.id %}">{{ protocol }}</a></td>
	<td>{% if protocol.wiki_page %}<a href="/wiki/{{protocol.wiki_page}}">ProtocolWiki</a>{% else %}no{% endif %}</td>
	<td>
<a href="{% url protocol-detail protocol.id %}"><img src="{{STATIC_URL}}img/icons/Zoom.png" width=25 alt="Detail"></a>
{% if perms.data.change_protocol %}
<a href="{% url protocol-edit protocol.id %}"><img src="/static/img/icons/Document Write.png" width=25 alt="Edit"></a>
{% endif %}
{% if perms.data.delete_protocol %}
<a href="{% url protocol-delete protocol.id %}"><img src="{{STATIC_URL}}img/icons/Close.png" width=25 alt="delete"></a>
{% endif %}
	</td>
</tr>
{% endfor %}
</tbody>
</table>

{% endblock content %}

data/templates/result_form.html
{% extends "base.html" %}
{% block head_title %}New Result for {{ experiment }}{% endblock %}
{% block title %}New Result {{experiment}}{% endblock %}
{% block content %}
<form enctype="multipart/form-data" method="POST" action="/experimentdb/experiment/{{experiment.experimentID}}/result/new/">{% csrf_token %}
<table>
{{form}}
</table>
 <input type="submit" value="Submit" />
 </form>
 
{% endblock %}